package medeia.generic

import medeia.decoder.DefaultBsonDecoderInstances
import medeia.encoder.DefaultBsonEncoderInstances

package object auto extends DefaultBsonDecoderInstances with DefaultBsonEncoderInstances with LowPriorityInstances

trait LowPriorityInstances extends GenericEncoderInstances with GenericDecoderInstances
